import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { IconArrowFork, IconHome, IconLogin, IconMessage, IconServicemark, IconUser } from "@tabler/icons-react";

import { FloatingNav } from "@/components/nava";

const navItems = [
  {
    name: "Home",
    link: "/",
    icon: <IconHome className="h-6 w-6 text-neutral-500 dark:text-white" />,
  },
  {
    name: "AboutUs",
    link: "/aboutUs",
    icon: <IconUser className="h-6 w-6 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Contact",
    link: "/contact",
    icon: (
      <IconMessage className="h-6 w-6 text-neutral-500 dark:text-white" />
    ),
  },
  {
    name: "services",
    link: "/services",
    icon: (
      <IconArrowFork className="h-6 w-6 text-neutral-500 dark:text-white " />
    ),
    
  },

  
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
        <FloatingNav navItems={navItems} />
        
        </div>
        
        {children}</body>
    </html>
  );
}
